/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

/**
 *
 * @author sebas
 */
public class MenuprincipalUI extends javax.swing.JFrame {
    public static String name2="";
    /**
     * Creates new form Ventana1inicio
     */
    public MenuprincipalUI() {
        
        initComponents();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        Boton_iniciar_simulacion = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabeiconomenu = new javax.swing.JLabel();
        Closebutton = new javax.swing.JButton();
        Label_icono = new javax.swing.JLabel();
        boton_carga_archivos1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Jtextfieldnciudades = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        textfield_alpha = new javax.swing.JTextField();
        TextFieldbeta = new javax.swing.JTextField();
        TextFieldaprendizaje = new javax.swing.JTextField();
        TextFieldevaporacion = new javax.swing.JTextField();
        TextFieldnhormigas = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 153, 102));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 600));
        jPanel1.setPreferredSize(new java.awt.Dimension(600, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Boton_iniciar_simulacion.setBackground(new java.awt.Color(51, 51, 51));
        Boton_iniciar_simulacion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Boton_iniciar_simulacion.setForeground(new java.awt.Color(0, 153, 153));
        Boton_iniciar_simulacion.setText("Iniciar simulacion");
        Boton_iniciar_simulacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_iniciar_simulacionActionPerformed(evt);
            }
        });
        jPanel1.add(Boton_iniciar_simulacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 560, 150, 30));

        jLabel1.setBackground(new java.awt.Color(255, 153, 153));
        jLabel1.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sistema Hormiga");
        jLabel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, new java.awt.Color(255, 102, 102), java.awt.Color.orange, java.awt.Color.orange));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 830, 40));
        jPanel1.add(jLabeiconomenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, -1, -1));

        Closebutton.setBackground(new java.awt.Color(51, 51, 51));
        Closebutton.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        Closebutton.setForeground(new java.awt.Color(0, 153, 153));
        Closebutton.setText("X");
        Closebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClosebuttonActionPerformed(evt);
            }
        });
        jPanel1.add(Closebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 30, 60, -1));

        Label_icono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/blackanthead_reescalada50.png"))); // NOI18N
        jPanel1.add(Label_icono, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, 250, 180));

        boton_carga_archivos1.setBackground(new java.awt.Color(51, 51, 51));
        boton_carga_archivos1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        boton_carga_archivos1.setForeground(new java.awt.Color(0, 153, 153));
        boton_carga_archivos1.setText("Carga de datos");
        boton_carga_archivos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_carga_archivos1ActionPerformed(evt);
            }
        });
        jPanel1.add(boton_carga_archivos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 160, -1));

        jPanel2.setForeground(new java.awt.Color(51, 51, 51));

        jLabel2.setBackground(new java.awt.Color(102, 102, 102));
        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 204));
        jLabel2.setText("Introducir numero de ciudades:");
        jPanel2.add(jLabel2);

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 190, 30));

        Jtextfieldnciudades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtextfieldnciudadesActionPerformed(evt);
            }
        });
        jPanel1.add(Jtextfieldnciudades, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, 130, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, -1, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 51, 0));
        jLabel3.setText("Alpha");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, -1, -1));

        jLabel4.setForeground(new java.awt.Color(255, 51, 0));
        jLabel4.setText("Beta");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 470, -1, -1));

        jLabel5.setForeground(new java.awt.Color(255, 51, 0));
        jLabel5.setText("Aprendizaje");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 470, -1, -1));

        jLabel6.setForeground(new java.awt.Color(204, 51, 0));
        jLabel6.setText("Evaporacion");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 470, -1, -1));

        jLabel7.setForeground(new java.awt.Color(204, 51, 0));
        jLabel7.setText("Numero de hormigas");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 470, -1, -1));

        textfield_alpha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfield_alphaActionPerformed(evt);
            }
        });
        jPanel1.add(textfield_alpha, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, 60, 20));

        TextFieldbeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldbetaActionPerformed(evt);
            }
        });
        jPanel1.add(TextFieldbeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 500, 60, 20));

        TextFieldaprendizaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldaprendizajeActionPerformed(evt);
            }
        });
        jPanel1.add(TextFieldaprendizaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 500, 70, -1));
        jPanel1.add(TextFieldevaporacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 500, 80, -1));

        TextFieldnhormigas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldnhormigasActionPerformed(evt);
            }
        });
        jPanel1.add(TextFieldnhormigas, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 500, 90, -1));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 153, 153));
        jLabel8.setText("Datos hormigas");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 430, 280, -1));

        jPanel3.setForeground(new java.awt.Color(102, 102, 102));
        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 550, 20));

        jButton1.setText("Confirmar datos de hormigas");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 550, 170, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Boton_iniciar_simulacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_iniciar_simulacionActionPerformed
       
        
    }//GEN-LAST:event_Boton_iniciar_simulacionActionPerformed

    private void ClosebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClosebuttonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ClosebuttonActionPerformed

    private void boton_carga_archivos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_carga_archivos1ActionPerformed
        Carga_archivos carga_archivos = new Carga_archivos();
        carga_archivos.setVisible(true);
    }//GEN-LAST:event_boton_carga_archivos1ActionPerformed

    private void JtextfieldnciudadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtextfieldnciudadesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtextfieldnciudadesActionPerformed

    private void textfield_alphaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfield_alphaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfield_alphaActionPerformed

    private void TextFieldbetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldbetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldbetaActionPerformed

    private void TextFieldaprendizajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldaprendizajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldaprendizajeActionPerformed

    private void TextFieldnhormigasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldnhormigasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldnhormigasActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuprincipalUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuprincipalUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuprincipalUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuprincipalUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MenuprincipalUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton_iniciar_simulacion;
    private javax.swing.JButton Closebutton;
    private javax.swing.JTextField Jtextfieldnciudades;
    private javax.swing.JLabel Label_icono;
    private javax.swing.JTextField TextFieldaprendizaje;
    private javax.swing.JTextField TextFieldbeta;
    private javax.swing.JTextField TextFieldevaporacion;
    private javax.swing.JTextField TextFieldnhormigas;
    private javax.swing.JButton boton_carga_archivos1;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabeiconomenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField textfield_alpha;
    // End of variables declaration//GEN-END:variables
}
