/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import java.awt.BorderLayout;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import org.graphstream.graph.Graph;
import org.graphstream.graph.implementations.*;
import org.graphstream.ui.swing_viewer.*;
import org.graphstream.ui.view.*;

import proyecto_1_edd.*;

/**
 *
 * @author sebastian.L
 */
public class MenuprincipalUI extends javax.swing.JFrame {
    public static String name2="";
    /**
     * Creates new form Ventana1inicio
     */
    
    int nCiudades;
    int nHormigas;
    
    int c_origen;
    int c_destino;
    
    int C;
    int a;
    int b;
    int q;
    double evaporacion;
    
    int c1;
    int c2;
    double tamaño;
    
    Grafo gr;
    ListaArista as = new ListaArista("as");
    
    DefaultTableModel mt = new DefaultTableModel();
    
    
    public MenuprincipalUI() {
        
        initComponents();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        
        String ids [] = {"Ciudad 1","Ciudad 2","Tamaño"};
        
        mt.setColumnIdentifiers(ids);
        
        jTable1.setModel(mt);
    }
    
    public void añadirArista(int c1, int c2, double aV) {
        as.InsertLast(c1, c2, aV);
    }
    
    public void eliminarArista(int c1, int c2, double aV) {
        int inX = as.SearchIndex(c1, c2);
        as.Delete(inX);
    }
    
    public void displayAristas() {
        as.ReadAll();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        Boton_iniciar_simulacion = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabeiconomenu = new javax.swing.JLabel();
        Closebutton = new javax.swing.JButton();
        Label_icono = new javax.swing.JLabel();
        boton_carga_archivos1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        JtextfieldCiudadDestino = new javax.swing.JTextField();
        textfield_alpha = new javax.swing.JTextField();
        TextFieldbeta = new javax.swing.JTextField();
        TextFieldaprendizaje = new javax.swing.JTextField();
        TextFieldevaporacion = new javax.swing.JTextField();
        TextFieldciclos = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        confirmarDatos = new javax.swing.JButton();
        TextFieldnhormigas = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jCiudadDestino = new javax.swing.JLabel();
        jCiudades = new javax.swing.JLabel();
        jCiclos = new javax.swing.JLabel();
        jAlpha = new javax.swing.JLabel();
        jBeta = new javax.swing.JLabel();
        jAprendizaje = new javax.swing.JLabel();
        jEvaporacion = new javax.swing.JLabel();
        jBotonEliminar = new javax.swing.JButton();
        jPanel17 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Jtextfieldnciudades = new javax.swing.JTextField();
        jPanel18 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        JtextfieldCiudadOrigen = new javax.swing.JTextField();
        jPanel19 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jHormigas = new javax.swing.JLabel();
        jCiudadOrigen = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jBotonAñadir = new javax.swing.JButton();
        jTextFieldCiudadUnion1 = new javax.swing.JTextField();
        jTextFieldAristaValor = new javax.swing.JTextField();
        jTextFieldCiudadUnion2 = new javax.swing.JTextField();
        jPanel22 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel23 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel24 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jBotonMostrarAristas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 153, 102));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 600));
        jPanel1.setPreferredSize(new java.awt.Dimension(600, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Boton_iniciar_simulacion.setBackground(new java.awt.Color(51, 51, 51));
        Boton_iniciar_simulacion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Boton_iniciar_simulacion.setForeground(new java.awt.Color(0, 153, 153));
        Boton_iniciar_simulacion.setText("Iniciar Simulación");
        Boton_iniciar_simulacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_iniciar_simulacionActionPerformed(evt);
            }
        });
        jPanel1.add(Boton_iniciar_simulacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 560, 150, 30));

        jLabel1.setBackground(new java.awt.Color(255, 153, 153));
        jLabel1.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sistema Hormiga");
        jLabel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, new java.awt.Color(255, 102, 102), java.awt.Color.orange, java.awt.Color.orange));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 830, 40));
        jPanel1.add(jLabeiconomenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, -1, -1));

        Closebutton.setBackground(new java.awt.Color(51, 51, 51));
        Closebutton.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        Closebutton.setForeground(new java.awt.Color(0, 153, 153));
        Closebutton.setText("X");
        Closebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClosebuttonActionPerformed(evt);
            }
        });
        jPanel1.add(Closebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 30, 60, -1));

        Label_icono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/blackanthead_reescalada50.png"))); // NOI18N
        jPanel1.add(Label_icono, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 120, 250, 180));

        boton_carga_archivos1.setBackground(new java.awt.Color(51, 51, 51));
        boton_carga_archivos1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        boton_carga_archivos1.setForeground(new java.awt.Color(0, 153, 153));
        boton_carga_archivos1.setText("Carga de datos");
        boton_carga_archivos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_carga_archivos1ActionPerformed(evt);
            }
        });
        jPanel1.add(boton_carga_archivos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 160, -1));

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setForeground(new java.awt.Color(51, 51, 51));

        jLabel2.setBackground(new java.awt.Color(102, 102, 102));
        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 204));
        jLabel2.setText("Introducir número de ciudades:");
        jPanel2.add(jLabel2);

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 190, 30));

        JtextfieldCiudadDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtextfieldCiudadDestinoActionPerformed(evt);
            }
        });
        jPanel1.add(JtextfieldCiudadDestino, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 130, -1));

        textfield_alpha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfield_alphaActionPerformed(evt);
            }
        });
        jPanel1.add(textfield_alpha, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, 60, 20));

        TextFieldbeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldbetaActionPerformed(evt);
            }
        });
        jPanel1.add(TextFieldbeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 500, 60, 20));

        TextFieldaprendizaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldaprendizajeActionPerformed(evt);
            }
        });
        jPanel1.add(TextFieldaprendizaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 500, 70, -1));

        TextFieldevaporacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldevaporacionActionPerformed(evt);
            }
        });
        jPanel1.add(TextFieldevaporacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 500, 80, -1));

        TextFieldciclos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldciclosActionPerformed(evt);
            }
        });
        jPanel1.add(TextFieldciclos, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 500, 90, -1));

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));
        jPanel3.setForeground(new java.awt.Color(102, 102, 102));

        jLabel4.setForeground(new java.awt.Color(0, 204, 204));
        jLabel4.setText("Número de Ciclos");
        jPanel3.add(jLabel4);

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 460, 110, 30));

        confirmarDatos.setText("Confirmar Datos");
        confirmarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarDatosActionPerformed(evt);
            }
        });
        jPanel1.add(confirmarDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 550, 170, -1));

        TextFieldnhormigas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldnhormigasActionPerformed(evt);
            }
        });
        jPanel1.add(TextFieldnhormigas, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 500, 90, -1));

        jPanel4.setBackground(new java.awt.Color(102, 102, 102));
        jPanel4.setForeground(new java.awt.Color(51, 51, 51));

        jLabel10.setBackground(new java.awt.Color(102, 102, 102));
        jLabel10.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 204, 204));
        jLabel10.setText("Ciudad Destino");
        jPanel4.add(jLabel10);

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 430, 100, 30));

        jPanel5.setBackground(new java.awt.Color(102, 102, 102));
        jPanel5.setForeground(new java.awt.Color(102, 102, 102));

        jLabel11.setForeground(new java.awt.Color(0, 204, 204));
        jLabel11.setText("Alpha");
        jPanel5.add(jLabel11);

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 70, 30));

        jPanel6.setBackground(new java.awt.Color(102, 102, 102));
        jPanel6.setForeground(new java.awt.Color(102, 102, 102));

        jLabel12.setForeground(new java.awt.Color(0, 204, 204));
        jLabel12.setText("Beta");
        jPanel6.add(jLabel12);

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 460, 70, 30));

        jPanel7.setBackground(new java.awt.Color(102, 102, 102));
        jPanel7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel7.setForeground(new java.awt.Color(102, 102, 102));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 153, 153));
        jLabel8.setText("Datos hormigas");
        jPanel7.add(jLabel8);

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 410, 230, 40));

        jPanel9.setBackground(new java.awt.Color(102, 102, 102));
        jPanel9.setForeground(new java.awt.Color(102, 102, 102));

        jLabel15.setForeground(new java.awt.Color(0, 204, 204));
        jLabel15.setText("Evaporación");
        jPanel9.add(jLabel15);

        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 460, 80, 30));

        jPanel10.setBackground(new java.awt.Color(102, 102, 102));
        jPanel10.setForeground(new java.awt.Color(102, 102, 102));

        jLabel16.setForeground(new java.awt.Color(0, 204, 204));
        jLabel16.setText("Número de hormigas");
        jPanel10.add(jLabel16);

        jPanel1.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 460, -1, 30));

        jPanel11.setBackground(new java.awt.Color(102, 102, 102));
        jPanel11.setForeground(new java.awt.Color(51, 51, 51));

        jLabel17.setBackground(new java.awt.Color(102, 102, 102));
        jLabel17.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 204, 204));
        jLabel17.setText("Ciudades");
        jPanel11.add(jLabel17);

        jPanel1.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 90, 80, 30));

        jPanel12.setBackground(new java.awt.Color(102, 102, 102));
        jPanel12.setForeground(new java.awt.Color(51, 51, 51));

        jLabel18.setBackground(new java.awt.Color(102, 102, 102));
        jLabel18.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 204, 204));
        jLabel18.setText("Ciclos");
        jPanel12.add(jLabel18);

        jPanel1.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 130, 80, 30));

        jPanel13.setBackground(new java.awt.Color(102, 102, 102));
        jPanel13.setForeground(new java.awt.Color(51, 51, 51));

        jLabel19.setBackground(new java.awt.Color(102, 102, 102));
        jLabel19.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 204, 204));
        jLabel19.setText("Alpha");
        jPanel13.add(jLabel19);

        jPanel1.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 170, 80, 30));

        jPanel14.setBackground(new java.awt.Color(102, 102, 102));
        jPanel14.setForeground(new java.awt.Color(51, 51, 51));

        jLabel20.setBackground(new java.awt.Color(102, 102, 102));
        jLabel20.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 204, 204));
        jLabel20.setText("Beta");
        jPanel14.add(jLabel20);

        jPanel1.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 210, 80, 30));

        jPanel15.setBackground(new java.awt.Color(102, 102, 102));
        jPanel15.setForeground(new java.awt.Color(51, 51, 51));

        jLabel21.setBackground(new java.awt.Color(102, 102, 102));
        jLabel21.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 204, 204));
        jLabel21.setText("Aprendizaje");
        jPanel15.add(jLabel21);

        jPanel1.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 250, 80, 30));

        jPanel16.setBackground(new java.awt.Color(102, 102, 102));
        jPanel16.setForeground(new java.awt.Color(51, 51, 51));

        jLabel22.setBackground(new java.awt.Color(102, 102, 102));
        jLabel22.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 204, 204));
        jLabel22.setText("Evaporación");
        jPanel16.add(jLabel22);

        jPanel1.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 290, 80, 30));

        jCiudadDestino.setBackground(new java.awt.Color(102, 102, 102));
        jCiudadDestino.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jCiudadDestino.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jCiudadDestino, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 430, 70, 20));

        jCiudades.setBackground(new java.awt.Color(102, 102, 102));
        jCiudades.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jCiudades.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jCiudades, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 100, 70, 20));

        jCiclos.setBackground(new java.awt.Color(102, 102, 102));
        jCiclos.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jCiclos.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jCiclos, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 140, 70, 20));

        jAlpha.setBackground(new java.awt.Color(102, 102, 102));
        jAlpha.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jAlpha.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jAlpha, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 180, 70, 20));

        jBeta.setBackground(new java.awt.Color(102, 102, 102));
        jBeta.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jBeta.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jBeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 220, 70, 20));

        jAprendizaje.setBackground(new java.awt.Color(102, 102, 102));
        jAprendizaje.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jAprendizaje.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jAprendizaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 260, 70, 20));

        jEvaporacion.setBackground(new java.awt.Color(102, 102, 102));
        jEvaporacion.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jEvaporacion.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jEvaporacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 300, 70, 20));

        jBotonEliminar.setText("Eliminar");
        jBotonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(jBotonEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 370, -1, -1));

        jPanel17.setBackground(new java.awt.Color(102, 102, 102));
        jPanel17.setForeground(new java.awt.Color(51, 51, 51));

        jLabel3.setBackground(new java.awt.Color(102, 102, 102));
        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 204, 204));
        jLabel3.setText("Ciudad de Origen:");
        jPanel17.add(jLabel3);

        jPanel1.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 120, 30));

        Jtextfieldnciudades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtextfieldnciudadesActionPerformed(evt);
            }
        });
        jPanel1.add(Jtextfieldnciudades, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 130, -1));

        jPanel18.setBackground(new java.awt.Color(102, 102, 102));
        jPanel18.setForeground(new java.awt.Color(51, 51, 51));

        jLabel5.setBackground(new java.awt.Color(102, 102, 102));
        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 204, 204));
        jLabel5.setText("Tamaño");
        jPanel18.add(jLabel5);

        jPanel1.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 320, 70, 30));

        JtextfieldCiudadOrigen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtextfieldCiudadOrigenActionPerformed(evt);
            }
        });
        jPanel1.add(JtextfieldCiudadOrigen, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 130, -1));

        jPanel19.setBackground(new java.awt.Color(102, 102, 102));
        jPanel19.setForeground(new java.awt.Color(51, 51, 51));

        jLabel23.setBackground(new java.awt.Color(102, 102, 102));
        jLabel23.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 204, 204));
        jLabel23.setText("Hormigas");
        jPanel19.add(jLabel23);

        jPanel1.add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 330, 80, 30));

        jPanel20.setBackground(new java.awt.Color(102, 102, 102));
        jPanel20.setForeground(new java.awt.Color(51, 51, 51));

        jLabel24.setBackground(new java.awt.Color(102, 102, 102));
        jLabel24.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 204, 204));
        jLabel24.setText("Ciudad Origen");
        jPanel20.add(jLabel24);

        jPanel1.add(jPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 390, 100, 30));

        jHormigas.setBackground(new java.awt.Color(102, 102, 102));
        jHormigas.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jHormigas.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jHormigas, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 340, 70, 20));

        jCiudadOrigen.setBackground(new java.awt.Color(102, 102, 102));
        jCiudadOrigen.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jCiudadOrigen.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jCiudadOrigen, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 400, 70, 20));

        jPanel21.setBackground(new java.awt.Color(102, 102, 102));
        jPanel21.setForeground(new java.awt.Color(102, 102, 102));

        jLabel25.setForeground(new java.awt.Color(0, 204, 204));
        jLabel25.setText("Aprendizaje");
        jPanel21.add(jLabel25);

        jPanel1.add(jPanel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 460, 80, 30));

        jBotonAñadir.setText("Añadir");
        jBotonAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonAñadirActionPerformed(evt);
            }
        });
        jPanel1.add(jBotonAñadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 370, -1, -1));

        jTextFieldCiudadUnion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCiudadUnion1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldCiudadUnion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, 60, -1));

        jTextFieldAristaValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAristaValorActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldAristaValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 320, 60, -1));

        jTextFieldCiudadUnion2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCiudadUnion2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldCiudadUnion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 280, 60, -1));

        jPanel22.setBackground(new java.awt.Color(102, 102, 102));
        jPanel22.setForeground(new java.awt.Color(51, 51, 51));

        jLabel6.setBackground(new java.awt.Color(102, 102, 102));
        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 204, 204));
        jLabel6.setText("Ciudad de Destino:");
        jPanel22.add(jLabel6);

        jPanel1.add(jPanel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 120, 30));

        jPanel23.setBackground(new java.awt.Color(102, 102, 102));
        jPanel23.setForeground(new java.awt.Color(51, 51, 51));

        jLabel7.setBackground(new java.awt.Color(102, 102, 102));
        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 204, 204));
        jLabel7.setText("Ciudad 1");
        jPanel23.add(jLabel7);

        jPanel1.add(jPanel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, 70, 30));

        jPanel24.setBackground(new java.awt.Color(102, 102, 102));
        jPanel24.setForeground(new java.awt.Color(51, 51, 51));

        jLabel9.setBackground(new java.awt.Color(102, 102, 102));
        jLabel9.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 204, 204));
        jLabel9.setText("Ciudad 2");
        jPanel24.add(jLabel9);

        jPanel1.add(jPanel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, 70, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Ciudad 1", "Ciudad 2", "Tamaño"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setPreferredSize(new java.awt.Dimension(360, 180));
        jScrollPane2.setViewportView(jTable1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 290, 160));

        jBotonMostrarAristas.setText("Mostrar Aristas");
        jBotonMostrarAristas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonMostrarAristasActionPerformed(evt);
            }
        });
        jPanel1.add(jBotonMostrarAristas, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Boton_iniciar_simulacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_iniciar_simulacionActionPerformed
        
        
    }//GEN-LAST:event_Boton_iniciar_simulacionActionPerformed

    private void ClosebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClosebuttonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ClosebuttonActionPerformed

    private void boton_carga_archivos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_carga_archivos1ActionPerformed
        Carga_archivos carga_archivos = new Carga_archivos();
        carga_archivos.setVisible(true);
    }//GEN-LAST:event_boton_carga_archivos1ActionPerformed

    private void JtextfieldCiudadDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtextfieldCiudadDestinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtextfieldCiudadDestinoActionPerformed

    private void textfield_alphaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfield_alphaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfield_alphaActionPerformed

    private void TextFieldbetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldbetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldbetaActionPerformed

    private void TextFieldaprendizajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldaprendizajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldaprendizajeActionPerformed

    private void TextFieldciclosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldciclosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldciclosActionPerformed

    private void confirmarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarDatosActionPerformed
        // TODO add your handling code here:
        
        try {
            nCiudades = Integer.parseInt(Jtextfieldnciudades.getText());
            nHormigas = Integer.parseInt(TextFieldnhormigas.getText());
            
            c_origen = Integer.parseInt(JtextfieldCiudadOrigen.getText());
            c_destino = Integer.parseInt(JtextfieldCiudadDestino.getText());

            a = Integer.parseInt(textfield_alpha.getText());
            b = Integer.parseInt(TextFieldbeta.getText());
            C = Integer.parseInt(TextFieldciclos.getText());
            q = Integer.parseInt(TextFieldaprendizaje.getText());

            evaporacion = Double.parseDouble(TextFieldevaporacion.getText());

            
            if(nCiudades > 20) {nCiudades = 20;}
            else if(nCiudades < 4) {nCiudades = 4;}
            
            if(nHormigas < 1) {nHormigas = 1;}
            
            jCiudades.setText(Integer.toString(nCiudades));
            jHormigas.setText(Integer.toString(nHormigas));
            
            
            
            if(a < 1) {a = 1;}
            if(b < 1) {b = 1;}
            if(q < 1) {q = 1;}
            if(C < 1) {C = 1;}
            
            if(evaporacion <= 0.0 || evaporacion >= 1.0) {
                evaporacion = 0.5;
                String errorMessage = "Error de dato: El factor de evaporación debe de estar en el intervalo (0,1).";
                JOptionPane.showMessageDialog(null, errorMessage);
            }
            
            jEvaporacion.setText(Double.toString(evaporacion));
            

            jAlpha.setText(Integer.toString(a));
            jBeta.setText(Integer.toString(b));
            jAprendizaje.setText(Integer.toString(q));
            jCiclos.setText(Integer.toString(C));
            
            if(c_origen == c_destino) {
                JOptionPane.showMessageDialog(null, "Error de dato: Ciudad de origen y ciudad de destino no pueden ser iguales.");
            }
            else if(c_origen > nCiudades || c_destino > nCiudades) {
                JOptionPane.showMessageDialog(null, "Error de dato: Las ciudades de origen y destino no pueden ser mayores a la cantidad de ciudades");
            }
            else {
                jCiudadOrigen.setText(Integer.toString(c_origen));
                jCiudadDestino.setText(Integer.toString(c_destino));
            }
            
            as.ReadAll();
        }
        catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Error de entrada de dato: Dato nulo o no válido.");
        }
    }//GEN-LAST:event_confirmarDatosActionPerformed

    private void TextFieldevaporacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldevaporacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldevaporacionActionPerformed

    private void TextFieldnhormigasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldnhormigasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldnhormigasActionPerformed

    private void jBotonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonEliminarActionPerformed
        // TODO add your handling code here:
        
        try {
            int row = jTable1.getSelectedRow();
            String temp1 = jTable1.getModel().getValueAt(row, 0).toString();
            String temp2 = jTable1.getModel().getValueAt(row, 1).toString();

            c1 = Integer.parseInt(temp1);
            c2 = Integer.parseInt(temp2);

            int inX = as.SearchIndex(c1 - 1, c2 - 1);
            as.Delete(inX - 1);

            mt.removeRow(jTable1.getSelectedRow());
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al eliminar arista: No se ha seleccionado una.");
        }
    }//GEN-LAST:event_jBotonEliminarActionPerformed

    private void JtextfieldnciudadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtextfieldnciudadesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtextfieldnciudadesActionPerformed

    private void JtextfieldCiudadOrigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtextfieldCiudadOrigenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtextfieldCiudadOrigenActionPerformed

    private void jBotonAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonAñadirActionPerformed
        // TODO add your handling code here:
        
        try {
            c1 = Integer.parseInt(jTextFieldCiudadUnion1.getText());
            c2 = Integer.parseInt(jTextFieldCiudadUnion2.getText());
            tamaño = Double.parseDouble(jTextFieldAristaValor.getText());
            
            
            if(!as.isEmpty()) {
                int inX = as.SearchIndex(c1 - 1, c2 - 1);
                Arista al = as.getArista(inX);
                if(c1 == al.src + 1 && c2 == al.dst + 1) {
                    return;
                }
                
            }
            
            
            
            /*
            if(c1 == Integer.parseInt(temp1) && c2 == Integer.parseInt(temp2)) {
                return;
            }
            */

            if(tamaño < 1) {
                JOptionPane.showMessageDialog(null, "Error al añadir arista: La distancia debe de ser mayor.");
                return;
            }

            if(c1 != c2 && c1 < nCiudades && c2 < nCiudades) {
                as.InsertLast(c1 - 1, c2 - 1, tamaño);
                mt.addRow(new Object[] {c1, c2, tamaño});
            }
            else {
                JOptionPane.showMessageDialog(null, "Error al añadir arista: Asegúrese de que los datos sean coherentes.");
            }
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al añadir arista: Asegúrese de que haya introducido los datos.");
        }
        
    }//GEN-LAST:event_jBotonAñadirActionPerformed

    private void jTextFieldCiudadUnion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCiudadUnion1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCiudadUnion1ActionPerformed

    private void jTextFieldCiudadUnion2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCiudadUnion2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCiudadUnion2ActionPerformed

    private void jTextFieldAristaValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAristaValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAristaValorActionPerformed

    private void jBotonMostrarAristasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonMostrarAristasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBotonMostrarAristasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuprincipalUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuprincipalUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuprincipalUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuprincipalUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MenuprincipalUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton_iniciar_simulacion;
    private javax.swing.JButton Closebutton;
    private javax.swing.JTextField JtextfieldCiudadDestino;
    private javax.swing.JTextField JtextfieldCiudadOrigen;
    private javax.swing.JTextField Jtextfieldnciudades;
    private javax.swing.JLabel Label_icono;
    private javax.swing.JTextField TextFieldaprendizaje;
    private javax.swing.JTextField TextFieldbeta;
    private javax.swing.JTextField TextFieldciclos;
    private javax.swing.JTextField TextFieldevaporacion;
    private javax.swing.JTextField TextFieldnhormigas;
    private javax.swing.JButton boton_carga_archivos1;
    private javax.swing.JButton confirmarDatos;
    private javax.swing.JLabel jAlpha;
    private javax.swing.JLabel jAprendizaje;
    private javax.swing.JLabel jBeta;
    private javax.swing.JButton jBotonAñadir;
    private javax.swing.JButton jBotonEliminar;
    private javax.swing.JButton jBotonMostrarAristas;
    private javax.swing.JLabel jCiclos;
    private javax.swing.JLabel jCiudadDestino;
    private javax.swing.JLabel jCiudadOrigen;
    private javax.swing.JLabel jCiudades;
    private javax.swing.JLabel jEvaporacion;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jHormigas;
    private javax.swing.JLabel jLabeiconomenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldAristaValor;
    private javax.swing.JTextField jTextFieldCiudadUnion1;
    private javax.swing.JTextField jTextFieldCiudadUnion2;
    private javax.swing.JTextField textfield_alpha;
    // End of variables declaration//GEN-END:variables
}
